---
- name: Deploy WebServer with Apache
  hosts: webserver
  vars:
    - var1: "Test"

  tasks:
    - name: Install http
      yum:
        name: httpd
        state: latest

    - name: Install php package
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - php
        - php-common
        - php-opcache
        - php-cli
        - php-gd
        - php-curl
        - php-mysqlnd
        - php-mysqli
    
    - name: Copy index.php file
      template:
        src: source/index.php.j2
        dest: /var/www/html/index.php

    - name: Webserver Runnig
      service:
        name: httpd
        state: started
        enabled: yes
